# Generated by Django 5.0.6 on 2024-06-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('correo', models.TextField(primary_key=True, serialize=False, verbose_name='Correo Usuario')),
                ('primerNombre', models.CharField(max_length=30, verbose_name='Primer Nombre')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuario',
            },
        ),
    ]
