# Generated by Django 5.0.6 on 2024-06-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='dui',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='DUI'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/', verbose_name='Fotografia'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Contraseña'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='primerApellido',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Primer Apellido'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='segundoApellido',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Apellido'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='segundoNombre',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Nombre'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Tipo De Usuario'),
        ),
    ]
