# Generated by Django 5.0.6 on 2024-06-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0002_usuario_direccion_usuario_dui_usuario_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Correo Usuario'),
        ),
    ]
