# Generated by Django 5.0.6 on 2024-06-17 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0003_alter_usuario_correo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPago', models.IntegerField(auto_created=True, verbose_name='Id Pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Total Carrito')),
                ('correo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Tienda.usuario', verbose_name='Correo Usuario')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'Pago',
            },
        ),
    ]
