# Generated by Django 5.0.6 on 2024-06-17 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0005_remove_pago_id_alter_pago_idpago_alter_pago_monto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('idFactura', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Id Factura')),
                ('totalFactura', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Total Factura')),
                ('fechaFactura', models.DateField(verbose_name='Fecha')),
                ('idCarro', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Tienda.carrito', verbose_name='Id Carro')),
                ('idPago', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Tienda.pago', verbose_name='Id Pago')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'Factura',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Id Producto')),
                ('nombreProducto', models.CharField(max_length=30, verbose_name='Nombre Del Producto')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio Unitario')),
                ('existencia', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='productos/', verbose_name='Imagen del Producto')),
                ('correo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Tienda.usuario', verbose_name='Correo Usuario')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='Detalle_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadProducto', models.IntegerField(verbose_name='Cantidad de Productos')),
                ('idCarrito', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Tienda.carrito', verbose_name='Id Carro')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Tienda.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle_Producto',
                'verbose_name_plural': 'Detalle_Productos',
                'db_table': 'Detalle_Producto',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idProveedor', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Id Proveedor')),
                ('nombreProveedor', models.CharField(max_length=30, verbose_name='Nombre Producto')),
                ('correo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Tienda.usuario', verbose_name='Correo Usuario')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'Proveedor',
            },
        ),
    ]
