# Generated by Django 5.0.6 on 2024-06-17 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0006_factura_producto_detalle_producto_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadCompra', models.IntegerField(auto_created=True, verbose_name='Cantidad Comprada')),
                ('fechaCompra', models.DateField(verbose_name='Fecha de Compra')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Tienda.producto', verbose_name='Id Producto')),
                ('idProveedor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Tienda.proveedor', verbose_name='Id Proveedor')),
            ],
            options={
                'verbose_name': 'Detalle_Compra',
                'verbose_name_plural': 'Detalle_Compras',
                'db_table': 'Detalle_Compra',
            },
        ),
    ]
